{"name": "Login In the Website", "status": "failed", "statusDetails": {"message": "Failure occurred and exit-on-failure mode is in use."}, "description": "This Test case do the login into the website.", "start": 1666105276864, "stop": 1666105276864, "uuid": "4c1ad939-5e10-4339-a4cf-8e530fd4907e", "historyId": "350ae30996177a364891c23f8a684d3c", "fullName": "TestCases.TestCase.Login In the Website", "labels": [{"name": "suite", "value": "TestCases"}, {"name": "subSuite", "value": "TestCase"}, {"name": "framework", "value": "robotframework"}, {"name": "language", "value": "cpython3"}, {"name": "host", "value": "MSDT081"}, {"name": "thread", "value": "default-5538b50a-eac0-4cc2-8db2-64e5dbdc92a8"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "robot:exit"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "robot:exit"}]}